### ISSUE TITLE
1.14.2 weird cactus error

### ISSUE THREAD

**Issue by coco5843** [kangarko/Remain#5]
Error:

`[16:45:27] [Server thread/ERROR]: Error occurred while enabling ProdigyGui v1.0.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at fr.cocoraid.prodigygui.loader.FileLoader.loadMenuSettings(FileLoader.java:169) ~[?:?]
	at fr.cocoraid.prodigygui.loader.FileLoader.lambda$0(FileLoader.java:55) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_201]
	at fr.cocoraid.prodigygui.loader.FileLoader.<init>(FileLoader.java:54) ~[?:?]
	at fr.cocoraid.prodigygui.ProdigyGUI.onEnable(ProdigyGUI.java:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:git-Spigot-0627955-649921e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [craftbukkit.jar:git-Spigot-0627955-649921e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit.jar:git-Spigot-0627955-649921e]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [craftbukkit.jar:git-Spigot-0627955-649921e]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [craftbukkit.jar:git-Spigot-0627955-649921e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [craftbukkit.jar:git-Spigot-0627955-649921e]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [craftbukkit.jar:git-Spigot-0627955-649921e]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [craftbukkit.jar:git-Spigot-0627955-649921e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException: Could not convert CompMaterial.CACTUS_GREEN to Bukkit Material!
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_201]
	at org.mineacademy.remain.model.CompMaterial.<init>(CompMaterial.java:958) ~[?:?]
	at org.mineacademy.remain.model.CompMaterial.<init>(CompMaterial.java:942) ~[?:?]
	at org.mineacademy.remain.model.CompMaterial.<clinit>(CompMaterial.java:139) ~[?:?]
	... 14 more
`

I do not use CACTUS_GREEN
but: RED_WOOL

and using lastest commit and laster spigot version:
` <version>22dbcaa</version>`

**Comment by kangarko** [comment]
Hi, I edited the file manually, you may want to organize imports: https://github.com/kangarko/Remain/blob/master/src/main/java/org/mineacademy/remain/model/CompMaterial.java

**Comment by kangarko** [comment]
And use GREEN_DYE instead of CACTUS_GREEN
